### ISSUE TITLE
while running test.py

### ISSUE THREAD

**Issue by kravi1220** [caiostringari/swantools#1]
I am getting error while running test.py

the error is like that

 P.spcplot(freqs,dirs,times[5],spectrum[5,:,:]*factors[5]) 
TypeError: string indices must be integers, not tuple

**Comment by caiostringari** [comment]
Hi, 

Swantools is now deprecated and not maintained anymore. Please refer to the oceanwaves package https://github.com/openearth/oceanwaves-python.

Cheers,
